### ISSUE TITLE
All temporal layers are shown in "Temporal" panel even if they are not visible

### ISSUE THREAD

**Issue by fergonco** [geoladris/plugins#22]
Temporal panel should show only temporal layers that are visible.

**Comment by victorzinho** [comment]
It should be fixed by https://github.com/csgis/geoladris-plugins/commit/f33fb37f685a0a16433da178f3e08f80ecd1a622.

**Comment by fergonco** [comment]
~~not fixed. I don't think this can be fixed in ui since it must sync two different components. Previously, l ayer-visibility events were heard and the panel updated.~~

Not tested with the last UI version. Testing in progress.

**Comment by fergonco** [comment]
It's fixed indeed.
