### ISSUE TITLE
time-slider does not raise an event when it is populated

### ISSUE THREAD

**Issue by fergonco** [geoladris/plugins#23]
time-slider must raise events as it gets populated (since the slider position changes). Currently it is not done and it results in the application being started with no time-slider.selection event sent. Therefore, the requests to temporal layers have no TIME parameter and all the different time instances are drawn, which can be a huge load to the server and provides a different visual result.

**Comment by victorzinho** [comment]
Fixed by https://github.com/geoladris/plugins/commit/2d827da21e5f95bf8e7c4a9daf796f5b03b05dcc.

**Comment by fergonco** [comment]
Confirmed.
