### ISSUE TITLE
Cannot interact with the map under layer list

### ISSUE THREAD

**Issue by fergonco** [geoladris/plugins#32]
Layer list does not allow mouse events to reach the map in the area that is south from the panel. For example, map pans stop if moved there and clicks for information are ignored.

Is there a "docking" panel in UI or is it easy to implement? If yes, we could redesign it so that the layer list is a docking panel on the left that can be shown or hidden. It may make #31 less noticeable.

**Comment by victorzinho** [comment]
It has been fixed with CSS.

There is a `sliding-div` component in `ui`, but it would probably need some adaptations (it was used just in a very specific scenario). In any case, I would open a new (non-blocking) issue if we want to do this.
