### ISSUE TITLE
add-layer and add-group no longer work

### ISSUE THREAD

**Issue by fergonco** [geoladris/plugins#5]
The events to add a layer and a group no longer work. They were "replaced" by an API that is not very intuitive and may expose some operations that are too low level. An example of both usages can be seen here: http://webinar-programacion.readthedocs.io/es/latest/programmer/#layers-loaded-add-layer-y-add-group

In general, the plugin that requires to manipulate the tree can decorate on demand and manage the decorators internally and we can keep a simple high level "event API".

**Comment by victorzinho** [comment]
Fixed by e46a957
